# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# blank line between shell prompts
add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

[directory]
fish_style_pwd_dir_length = 1
style = 'blue'

[git_branch]
format = '[$branch]($style) '

[git_metrics]
disabled = false

[git_status]
style       = 'blue'
deleted     = '[â¨¯](red)'
modified    = '[Â±](yellow)'
staged      = '[ğŸ—¸](green)'
ahead       = '[ğŸ ‰](green)'
behind      = '[ğŸ ‹](red)'
